// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

contract CheerUp {

    // motivational messages
    string[] public messages = [
        'Stay positive, work hard, make it happen.',
        'Dream big and dare to fail.',
        'Dream big and dare to fail.',
        'Push through the pain.',
        'Success starts with self-belief.',
        'Dream big and dare to fail.',
        'Stay positive, work hard, make it happen.',
        'Believe in yourself.',
        'Your only limit is your mind.',
        'Success starts with self-belief.',
        'Success starts with self-belief.',
        'Believe in yourself.',
        'Your only limit is your mind.',
        'Never give up on your dreams.',
        'Dream big and dare to fail.',
        'Success starts with self-belief.',
        'Your only limit is your mind.',
        'Believe in yourself.',
        'The harder you work, the luckier you get.',
        'Dream big and dare to fail.',
        'Never give up on your dreams.',
        'Believe in yourself.',
        'You are capable of amazing things.',
        'Success starts with self-belief.',
        'Dream big and dare to fail.',
        'Stay positive, work hard, make it happen.',
        'Stay positive, work hard, make it happen.',
        'You are capable of amazing things.',
        'Never give up on your dreams.',
        'Stay positive, work hard, make it happen.',
        'Success starts with self-belief.',
        'Dream big and dare to fail.',
        'Every step forward is a step toward success.',
        'Push through the pain.',
        'Your only limit is your mind.',
        'Believe in yourself.',
        'Your only limit is your mind.',
        'You are capable of amazing things.',
        'Dream big and dare to fail.',
        'Your only limit is your mind.',
        'Believe in yourself.',
        'Believe in yourself.',
        'Your only limit is your mind.',
        'The harder you work, the luckier you get.',
        'You are capable of amazing things.',
        'Push through the pain.',
        'Push through the pain.',
        'You are capable of amazing things.',
        'You are capable of amazing things.',
        'Never give up on your dreams.',
        'Your only limit is your mind.',
        'You are capable of amazing things.',
        'Success starts with self-belief.',
        'Dream big and dare to fail.',
        'You are capable of amazing things.',
        'Never give up on your dreams.',
        'Every step forward is a step toward success.',
        'Every step forward is a step toward success.',
        'Your only limit is your mind.',
        'You are capable of amazing things.',
        'Never give up on your dreams.',
        'You are capable of amazing things.',
        'Never give up on your dreams.',
        'Dream big and dare to fail.',
        'Dream big and dare to fail.',
        'You are capable of amazing things.',
        'Dream big and dare to fail.',
        'Never give up on your dreams.',
        'The harder you work, the luckier you get.',
        'Every step forward is a step toward success.',
        'Dream big and dare to fail.',
        'Your only limit is your mind.',
        'Every step forward is a step toward success.',
        'Your only limit is your mind.',
        'Believe in yourself.',
        'The harder you work, the luckier you get.',
        'Push through the pain.',
        'Dream big and dare to fail.',
        'Push through the pain.',
        'Your only limit is your mind.',
        'Push through the pain.',
        'Dream big and dare to fail.',
        'Every step forward is a step toward success.',
        'Every step forward is a step toward success.',
        'Dream big and dare to fail.',
        'Stay positive, work hard, make it happen.',
        'Believe in yourself.',
        'Push through the pain.',
        'Dream big and dare to fail.',
        'Believe in yourself.',
        'Success starts with self-belief.',
        'You are capable of amazing things.',
        'Dream big and dare to fail.',
        'Never give up on your dreams.',
        'Dream big and dare to fail.',
        'Your only limit is your mind.',
        'The harder you work, the luckier you get.',
        'Every step forward is a step toward success.',
        'The harder you work, the luckier you get.',
        'Push through the pain.',
        'Your only limit is your mind.',
        'Push through the pain.',
        'Stay positive, work hard, make it happen.',
        'Dream big and dare to fail.',
        'Stay positive, work hard, make it happen.',
        'Every step forward is a step toward success.',
        'Push through the pain.',
        'Your only limit is your mind.',
        'Success starts with self-belief.',
        'Believe in yourself.',
        'Your only limit is your mind.',
        'Stay positive, work hard, make it happen.',
        'Dream big and dare to fail.',
        'Never give up on your dreams.',
        'The harder you work, the luckier you get.',
        'Your only limit is your mind.',
        'Success starts with self-belief.',
        'Your only limit is your mind.',
        'The harder you work, the luckier you get.',
        'Your only limit is your mind.',
        'Every step forward is a step toward success.',
        'Success starts with self-belief.',
        'Never give up on your dreams.',
        'Every step forward is a step toward success.',
        'You are capable of amazing things.',
        'Stay positive, work hard, make it happen.',
        'Your only limit is your mind.',
        'Push through the pain.',
        'Stay positive, work hard, make it happen.',
        'Dream big and dare to fail.',
        'Never give up on your dreams.',
        'Your only limit is your mind.',
        'Your only limit is your mind.',
        'Never give up on your dreams.',
        'Stay positive, work hard, make it happen.',
        'The harder you work, the luckier you get.',
        'The harder you work, the luckier you get.',
        'Never give up on your dreams.',
        'Dream big and dare to fail.',
        'Your only limit is your mind.',
        'Believe in yourself.',
        'Push through the pain.',
        'You are capable of amazing things.',
        'Your only limit is your mind.',
        'You are capable of amazing things.',
        'Every step forward is a step toward success.',
        'Your only limit is your mind.',
        'Stay positive, work hard, make it happen.',
        'Success starts with self-belief.',
        'The harder you work, the luckier you get.',
        'Your only limit is your mind.',
        'Never give up on your dreams.',
        'Stay positive, work hard, make it happen.',
        'Stay positive, work hard, make it happen.',
        'You are capable of amazing things.',
        'Every step forward is a step toward success.',
        'The harder you work, the luckier you get.',
        'Dream big and dare to fail.',
        'Never give up on your dreams.',
        'Believe in yourself.',
        'Push through the pain.',
        'Never give up on your dreams.',
        'Never give up on your dreams.',
        'Never give up on your dreams.',
        'Every step forward is a step toward success.',
        'Stay positive, work hard, make it happen.',
        'Never give up on your dreams.',
        'Never give up on your dreams.',
        'Dream big and dare to fail.',
        'Stay positive, work hard, make it happen.',
        'Push through the pain.',
        'The harder you work, the luckier you get.',
        'Dream big and dare to fail.',
        'Push through the pain.',
        'Every step forward is a step toward success.',
        'Believe in yourself.',
        'Every step forward is a step toward success.',
        'You are capable of amazing things.',
        'Stay positive, work hard, make it happen.',
        'Success starts with self-belief.',
        'Believe in yourself.',
        'The harder you work, the luckier you get.',
        'Your only limit is your mind.',
        'Stay positive, work hard, make it happen.',
        'You are capable of amazing things.',
        'The harder you work, the luckier you get.',
        'The harder you work, the luckier you get.',
        'Dream big and dare to fail.',
        'Stay positive, work hard, make it happen.',
        'Your only limit is your mind.',
        'Dream big and dare to fail.',
        'Success starts with self-belief.',
        'The harder you work, the luckier you get.',
        'Success starts with self-belief.',
        'Believe in yourself.',
        'Every step forward is a step toward success.',
        'Push through the pain.',
        'Success starts with self-belief.',
        'Your only limit is your mind.',
        'Dream big and dare to fail.',
        'You are capable of amazing things.',
        'Push through the pain.',
        'Believe in yourself.',
        'Believe in yourself.',
        'Never give up on your dreams.',
        'The harder you work, the luckier you get.',
        'Dream big and dare to fail.',
        'Stay positive, work hard, make it happen.',
        'The harder you work, the luckier you get.',
        'Every step forward is a step toward success.',
        'You are capable of amazing things.',
        'Dream big and dare to fail.',
        'Never give up on your dreams.',
        'Dream big and dare to fail.',
        'Believe in yourself.',
        'Push through the pain.',
        'Your only limit is your mind.',
        'Believe in yourself.',
        'Success starts with self-belief.',
        'Push through the pain.',
        'Your only limit is your mind.',
        'Dream big and dare to fail.',
        'Dream big and dare to fail.',
        'The harder you work, the luckier you get.',
        'You are capable of amazing things.',
        'The harder you work, the luckier you get.',
        'Believe in yourself.',
        'You are capable of amazing things.',
        'Push through the pain.',
        'Never give up on your dreams.',
        'The harder you work, the luckier you get.',
        'Never give up on your dreams.',
        'Every step forward is a step toward success.',
        'Never give up on your dreams.',
        'You are capable of amazing things.',
        'Every step forward is a step toward success.',
        'Dream big and dare to fail.',
        'You are capable of amazing things.',
        'You are capable of amazing things.',
        'Believe in yourself.',
        'Dream big and dare to fail.',
        'Your only limit is your mind.',
        'Never give up on your dreams.',
        'Believe in yourself.',
        'Never give up on your dreams.',
        'You are capable of amazing things.',
        'You are capable of amazing things.',
        'The harder you work, the luckier you get.',
        'Every step forward is a step toward success.',
        'Dream big and dare to fail.',
        'Success starts with self-belief.',
        'Stay positive, work hard, make it happen.',
        'Every step forward is a step toward success.',
        'Success starts with self-belief.',
        'Push through the pain.',
        'Every step forward is a step toward success.',
        'Dream big and dare to fail.',
        'The harder you work, the luckier you get.',
        'Your only limit is your mind.',
        'Every step forward is a step toward success.',
        'Dream big and dare to fail.',
        'Success starts with self-belief.',
        'Never give up on your dreams.',
        'Success starts with self-belief.',
        'Never give up on your dreams.',
        'Dream big and dare to fail.',
        'You are capable of amazing things.',
        'Never give up on your dreams.',
        'Dream big and dare to fail.',
        'Believe in yourself.',
        'Push through the pain.',
        'You are capable of amazing things.',
        'The harder you work, the luckier you get.',
        'Your only limit is your mind.',
        'Success starts with self-belief.',
        'Every step forward is a step toward success.',
        'Your only limit is your mind.',
        'Your only limit is your mind.',
        'You are capable of amazing things.',
        'Dream big and dare to fail.',
        'Push through the pain.',
        'Push through the pain.',
        'Your only limit is your mind.',
        'Dream big and dare to fail.',
        'The harder you work, the luckier you get.',
        'Push through the pain.',
        'Stay positive, work hard, make it happen.',
        'Never give up on your dreams.',
        'Push through the pain.',
        'Success starts with self-belief.',
        'Stay positive, work hard, make it happen.',
        'Your only limit is your mind.',
        'Every step forward is a step toward success.',
        'Dream big and dare to fail.',
        'Dream big and dare to fail.',
        'Success starts with self-belief.',
        'Your only limit is your mind.',
        'Every step forward is a step toward success.',
        'The harder you work, the luckier you get.',
        'Every step forward is a step toward success.',
        'The harder you work, the luckier you get.',
        'The harder you work, the luckier you get.',
        'Every step forward is a step toward success.',
        'Believe in yourself.',
        'Stay positive, work hard, make it happen.',
        'Believe in yourself.',
        'Believe in yourself.',
        'Never give up on your dreams.',
        'Success starts with self-belief.',
        'Believe in yourself.',
        'Dream big and dare to fail.',
        'The harder you work, the luckier you get.',
        'The harder you work, the luckier you get.',
        'Every step forward is a step toward success.',
        'Never give up on your dreams.',
        'Believe in yourself.',
        'Never give up on your dreams.',
        'Dream big and dare to fail.',
        'Never give up on your dreams.',
        'The harder you work, the luckier you get.',
        'Your only limit is your mind.',
        'Push through the pain.',
        'Push through the pain.',
        'Never give up on your dreams.',
        'The harder you work, the luckier you get.',
        'Success starts with self-belief.',
        'Your only limit is your mind.',
        'Success starts with self-belief.',
        'The harder you work, the luckier you get.',
        'Your only limit is your mind.',
        'Every step forward is a step toward success.',
        'Success starts with self-belief.',
        'Believe in yourself.',
        'Believe in yourself.',
        'The harder you work, the luckier you get.',
        'Stay positive, work hard, make it happen.',
        'Every step forward is a step toward success.',
        'The harder you work, the luckier you get.',
        'Your only limit is your mind.',
        'Believe in yourself.',
        'Believe in yourself.',
        'Your only limit is your mind.',
        'Success starts with self-belief.',
        'Every step forward is a step toward success.',
        'Success starts with self-belief.',
        'Success starts with self-belief.',
        'Never give up on your dreams.',
        'Every step forward is a step toward success.',
        'Every step forward is a step toward success.',
        'Your only limit is your mind.',
        'Your only limit is your mind.',
        'Push through the pain.',
        'The harder you work, the luckier you get.',
        'Stay positive, work hard, make it happen.',
        'The harder you work, the luckier you get.',
        'Believe in yourself.',
        'Dream big and dare to fail.',
        'Dream big and dare to fail.',
        'The harder you work, the luckier you get.',
        'Stay positive, work hard, make it happen.',
        'Dream big and dare to fail.',
        'Success starts with self-belief.',
        'The harder you work, the luckier you get.',
        'Your only limit is your mind.',
        'You are capable of amazing things.',
        'Dream big and dare to fail.',
        'Dream big and dare to fail.',
        'Never give up on your dreams.',
        'Believe in yourself.',
        'Your only limit is your mind.',
        'Dream big and dare to fail.',
        'Never give up on your dreams.',
        'Dream big and dare to fail.',
        'Success starts with self-belief.',
        'Never give up on your dreams.',
        'Every step forward is a step toward success.',
        'Push through the pain.',
        'Dream big and dare to fail.',
        'You are capable of amazing things.',
        'Never give up on your dreams.',
        'Never give up on your dreams.',
        'Push through the pain.',
        'Your only limit is your mind.',
        'The harder you work, the luckier you get.',
        'Your only limit is your mind.',
        'Push through the pain.',
        'Believe in yourself.',
        'Believe in yourself.',
        'Never give up on your dreams.',
        'Believe in yourself.',
        'Your only limit is your mind.',
        'Push through the pain.',
        'You are capable of amazing things.',
        'Dream big and dare to fail.',
        'Dream big and dare to fail.',
        'The harder you work, the luckier you get.',
        'Every step forward is a step toward success.',
        'The harder you work, the luckier you get.',
        'Never give up on your dreams.',
        'You are capable of amazing things.',
        'Dream big and dare to fail.',
        'Success starts with self-belief.',
        'Believe in yourself.',
        'Believe in yourself.',
        'Never give up on your dreams.',
        'Believe in yourself.',
        'Dream big and dare to fail.',
        'Your only limit is your mind.',
        'Believe in yourself.',
        'You are capable of amazing things.',
        'Dream big and dare to fail.',
        'Believe in yourself.',
        'You are capable of amazing things.',
        'Push through the pain.',
        'Stay positive, work hard, make it happen.',
        'Push through the pain.',
        'Never give up on your dreams.',
        'Stay positive, work hard, make it happen.',
        'Stay positive, work hard, make it happen.',
        'Never give up on your dreams.',
        'You are capable of amazing things.',
        'Never give up on your dreams.',
        'Believe in yourself.',
        'The harder you work, the luckier you get.',
        'Every step forward is a step toward success.',
        'Never give up on your dreams.',
        'Push through the pain.',
        'Your only limit is your mind.',
        'Never give up on your dreams.',
        'Your only limit is your mind.',
        'Never give up on your dreams.',
        'Your only limit is your mind.',
        'Believe in yourself.',
        'The harder you work, the luckier you get.',
        'Push through the pain.',
        'Your only limit is your mind.',
        'Never give up on your dreams.',
        'Your only limit is your mind.',
        'Push through the pain.',
        'Believe in yourself.',
        'You are capable of amazing things.',
        'Success starts with self-belief.',
        'Stay positive, work hard, make it happen.',
        'Success starts with self-belief.',
        'Dream big and dare to fail.',
        'Success starts with self-belief.',
        'Never give up on your dreams.',
        'Your only limit is your mind.',
        'Dream big and dare to fail.',
        'Stay positive, work hard, make it happen.',
        'Every step forward is a step toward success.',
        'Your only limit is your mind.',
        'Every step forward is a step toward success.',
        'The harder you work, the luckier you get.',
        'Dream big and dare to fail.',
        'You are capable of amazing things.',
        'The harder you work, the luckier you get.',
        'Dream big and dare to fail.',
        'Stay positive, work hard, make it happen.',
        'Push through the pain.',
        'Success starts with self-belief.',
        'Every step forward is a step toward success.',
        'Stay positive, work hard, make it happen.',
        'Every step forward is a step toward success.',
        'Never give up on your dreams.',
        'Never give up on your dreams.',
        'Stay positive, work hard, make it happen.',
        'Push through the pain.',
        'Dream big and dare to fail.',
        'Believe in yourself.',
        'Stay positive, work hard, make it happen.',
        'Never give up on your dreams.',
        'Every step forward is a step toward success.',
        'Never give up on your dreams.',
        'Success starts with self-belief.',
        'The harder you work, the luckier you get.',
        'Stay positive, work hard, make it happen.',
        'Push through the pain.',
        'Your only limit is your mind.',
        'Dream big and dare to fail.',
        'Dream big and dare to fail.',
        'Your only limit is your mind.',
        'Your only limit is your mind.',
        'Push through the pain.',
        'Believe in yourself.',
        'Your only limit is your mind.',
        'You are capable of amazing things.',
        'The harder you work, the luckier you get.',
        'Success starts with self-belief.',
        'Believe in yourself.',
        'Dream big and dare to fail.',
        'Success starts with self-belief.',
        'Every step forward is a step toward success.',
        'Push through the pain.',
        'Stay positive, work hard, make it happen.',
        'Stay positive, work hard, make it happen.',
        'Your only limit is your mind.',
        'You are capable of amazing things.',
        'The harder you work, the luckier you get.',
        'Believe in yourself.',
        'The harder you work, the luckier you get.',
        'Never give up on your dreams.',
        'Your only limit is your mind.',
        'Never give up on your dreams.',
        'Never give up on your dreams.',
        'Dream big and dare to fail.',
        'Never give up on your dreams.',
        'Every step forward is a step toward success.',
        'Never give up on your dreams.',
        'Never give up on your dreams.',
        'Success starts with self-belief.',
        'Success starts with self-belief.',
        'Believe in yourself.',
        'Success starts with self-belief.',
        'Push through the pain.',
        'Never give up on your dreams.',
        'You are capable of amazing things.',
        'Stay positive, work hard, make it happen.',
        'Your only limit is your mind.',
        'You are capable of amazing things.',
        'Never give up on your dreams.',
        'Push through the pain.',
        'You are capable of amazing things.',
        'Your only limit is your mind.',
        'The harder you work, the luckier you get.',
        'Success starts with self-belief.',
        'You are capable of amazing things.',
        'You are capable of amazing things.',
        'The harder you work, the luckier you get.',
        'Every step forward is a step toward success.',
        'Believe in yourself.',
        'Stay positive, work hard, make it happen.',
        'Stay positive, work hard, make it happen.',
        'Dream big and dare to fail.',
        'Dream big and dare to fail.',
        'Push through the pain.',
        'Dream big and dare to fail.',
        'Your only limit is your mind.',
        'Stay positive, work hard, make it happen.',
        'Every step forward is a step toward success.',
        'Believe in yourself.',
        'Every step forward is a step toward success.',
        'Dream big and dare to fail.',
        'You are capable of amazing things.',
        'Believe in yourself.',
        'The harder you work, the luckier you get.',
        'Stay positive, work hard, make it happen.',
        'Stay positive, work hard, make it happen.',
        'Believe in yourself.',
        'Every step forward is a step toward success.',
        'Success starts with self-belief.',
        'Success starts with self-belief.',
        'Dream big and dare to fail.',
        'Your only limit is your mind.',
        'Your only limit is your mind.',
        'Dream big and dare to fail.',
        'Success starts with self-belief.',
        'Never give up on your dreams.',
        'Never give up on your dreams.',
        'Your only limit is your mind.',
        'Success starts with self-belief.',
        'Push through the pain.',
        'Dream big and dare to fail.',
        'Believe in yourself.',
        'Dream big and dare to fail.',
        'Success starts with self-belief.',
        'Dream big and dare to fail.',
        'Dream big and dare to fail.',
        'Stay positive, work hard, make it happen.',
        'Dream big and dare to fail.',
        'You are capable of amazing things.',
        'Your only limit is your mind.',
        'Every step forward is a step toward success.',
        'Success starts with self-belief.',
        'The harder you work, the luckier you get.',
        'Your only limit is your mind.',
        'Stay positive, work hard, make it happen.',
        'Stay positive, work hard, make it happen.',
        'Stay positive, work hard, make it happen.',
        'Push through the pain.',
        'Dream big and dare to fail.',
        'You are capable of amazing things.',
        'The harder you work, the luckier you get.',
        'Push through the pain.',
        'Push through the pain.',
        'Believe in yourself.',
        'Push through the pain.',
        'The harder you work, the luckier you get.',
        'Believe in yourself.',
        'Never give up on your dreams.',
        'Stay positive, work hard, make it happen.',
        'Your only limit is your mind.',
        'Believe in yourself.',
        'The harder you work, the luckier you get.',
        'Your only limit is your mind.',
        'Dream big and dare to fail.',
        'Push through the pain.',
        'Push through the pain.',
        'Stay positive, work hard, make it happen.',
        'Believe in yourself.',
        'Stay positive, work hard, make it happen.',
        'Dream big and dare to fail.',
        'Dream big and dare to fail.',
        'Success starts with self-belief.',
        'Stay positive, work hard, make it happen.',
        'Your only limit is your mind.',
        'You are capable of amazing things.',
        'Your only limit is your mind.',
        'Push through the pain.',
        'Never give up on your dreams.',
        'The harder you work, the luckier you get.',
        'Dream big and dare to fail.',
        'Never give up on your dreams.',
        'Never give up on your dreams.',
        'Dream big and dare to fail.',
        'Success starts with self-belief.',
        'Every step forward is a step toward success.',
        'The harder you work, the luckier you get.',
        'Every step forward is a step toward success.',
        'You are capable of amazing things.',
        'Every step forward is a step toward success.',
        'Push through the pain.',
        'Never give up on your dreams.',
        'Dream big and dare to fail.',
        'Push through the pain.',
        'Every step forward is a step toward success.',
        'Every step forward is a step toward success.',
        'You are capable of amazing things.',
        'Never give up on your dreams.',
        'Success starts with self-belief.',
        'Every step forward is a step toward success.',
        'Believe in yourself.',
        'Push through the pain.',
        'Never give up on your dreams.',
        'Success starts with self-belief.',
        'Dream big and dare to fail.',
        'Every step forward is a step toward success.',
        'Stay positive, work hard, make it happen.',
        'Your only limit is your mind.',
        'Never give up on your dreams.',
        'Believe in yourself.',
        'Dream big and dare to fail.',
        'Your only limit is your mind.',
        'Your only limit is your mind.',
        'Stay positive, work hard, make it happen.',
        'Stay positive, work hard, make it happen.',
        'Dream big and dare to fail.',
        'Success starts with self-belief.',
        'Your only limit is your mind.',
        'Believe in yourself.',
        'Stay positive, work hard, make it happen.',
        'Your only limit is your mind.',
        'Dream big and dare to fail.',
        'Believe in yourself.',
        'Success starts with self-belief.',
        'Believe in yourself.',
        'Stay positive, work hard, make it happen.',
        'Push through the pain.',
        'Stay positive, work hard, make it happen.',
        'Stay positive, work hard, make it happen.',
        'You are capable of amazing things.',
        'Your only limit is your mind.',
        'You are capable of amazing things.',
        'Believe in yourself.',
        'The harder you work, the luckier you get.',
        'The harder you work, the luckier you get.',
        'Dream big and dare to fail.',
        'Never give up on your dreams.',
        'The harder you work, the luckier you get.',
        'Success starts with self-belief.',
        'Never give up on your dreams.',
        'Dream big and dare to fail.',
        'The harder you work, the luckier you get.',
        'Your only limit is your mind.',
        'Your only limit is your mind.',
        'The harder you work, the luckier you get.',
        'Never give up on your dreams.',
        'The harder you work, the luckier you get.',
        'Push through the pain.',
        'Dream big and dare to fail.',
        'Believe in yourself.',
        'Believe in yourself.',
        'Every step forward is a step toward success.',
        'Every step forward is a step toward success.',
        'Stay positive, work hard, make it happen.',
        'Never give up on your dreams.',
        'Your only limit is your mind.',
        'You are capable of amazing things.',
        'Success starts with self-belief.',
        'Success starts with self-belief.',
        'Success starts with self-belief.',
        'You are capable of amazing things.',
        'Stay positive, work hard, make it happen.',
        'You are capable of amazing things.',
        'Never give up on your dreams.',
        'The harder you work, the luckier you get.',
        'Push through the pain.',
        'Dream big and dare to fail.',
        'Your only limit is your mind.',
        'Never give up on your dreams.',
        'Dream big and dare to fail.',
        'Push through the pain.',
        'Dream big and dare to fail.',
        'The harder you work, the luckier you get.',
        'The harder you work, the luckier you get.',
        'Believe in yourself.',
        'Success starts with self-belief.',
        'Success starts with self-belief.',
        'You are capable of amazing things.',
        'Never give up on your dreams.',
        'The harder you work, the luckier you get.',
        'You are capable of amazing things.',
        'Push through the pain.',
        'Believe in yourself.',
        'Stay positive, work hard, make it happen.',
        'The harder you work, the luckier you get.',
        'Stay positive, work hard, make it happen.',
        'Believe in yourself.',
        'Success starts with self-belief.',
        'You are capable of amazing things.',
        'You are capable of amazing things.',
        'Stay positive, work hard, make it happen.',
        'You are capable of amazing things.',
        'Success starts with self-belief.',
        'Never give up on your dreams.',
        'Believe in yourself.',
        'Your only limit is your mind.',
        'The harder you work, the luckier you get.',
        'Your only limit is your mind.',
        'You are capable of amazing things.',
        'You are capable of amazing things.',
        'Dream big and dare to fail.',
        'The harder you work, the luckier you get.',
        'Dream big and dare to fail.',
        'Stay positive, work hard, make it happen.',
        'The harder you work, the luckier you get.',
        'Push through the pain.',
        'Believe in yourself.',
        'Believe in yourself.',
        'Stay positive, work hard, make it happen.',
        'Success starts with self-belief.',
        'Believe in yourself.',
        'Every step forward is a step toward success.',
        'You are capable of amazing things.',
        'You are capable of amazing things.',
        'Success starts with self-belief.',
        'You are capable of amazing things.',
        'Success starts with self-belief.',
        'The harder you work, the luckier you get.',
        'Never give up on your dreams.',
        'Success starts with self-belief.',
        'Never give up on your dreams.',
        'Stay positive, work hard, make it happen.',
        'Success starts with self-belief.',
        'Success starts with self-belief.',
        'Your only limit is your mind.',
        'Believe in yourself.',
        'Push through the pain.',
        'Success starts with self-belief.',
        'The harder you work, the luckier you get.',
        'Push through the pain.',
        'Push through the pain.',
        'Your only limit is your mind.',
        'Dream big and dare to fail.',
        'Your only limit is your mind.',
        'Never give up on your dreams.',
        'Push through the pain.',
        'Believe in yourself.',
        'The harder you work, the luckier you get.',
        'Dream big and dare to fail.',
        'The harder you work, the luckier you get.',
        'Dream big and dare to fail.',
        'Never give up on your dreams.',
        'Push through the pain.',
        'Your only limit is your mind.',
        'Every step forward is a step toward success.',
        'Success starts with self-belief.',
        'Never give up on your dreams.',
        'Believe in yourself.',
        'Dream big and dare to fail.',
        'Dream big and dare to fail.',
        'You are capable of amazing things.',
        'Stay positive, work hard, make it happen.',
        'Never give up on your dreams.',
        'Success starts with self-belief.',
        'Believe in yourself.',
        'The harder you work, the luckier you get.',
        'Push through the pain.',
        'Push through the pain.',
        'Success starts with self-belief.',
        'Dream big and dare to fail.',
        'Push through the pain.',
        'Dream big and dare to fail.',
        'Every step forward is a step toward success.',
        'Stay positive, work hard, make it happen.',
        'Every step forward is a step toward success.',
        'Never give up on your dreams.',
        'Push through the pain.',
        'Stay positive, work hard, make it happen.',
        'Push through the pain.',
        'Stay positive, work hard, make it happen.',
        'Dream big and dare to fail.',
        'Believe in yourself.',
        'Success starts with self-belief.',
        'Push through the pain.',
        'You are capable of amazing things.',
        'Stay positive, work hard, make it happen.',
        'Every step forward is a step toward success.',
        'Your only limit is your mind.',
        'Success starts with self-belief.',
        'Believe in yourself.',
        'Every step forward is a step toward success.',
        'You are capable of amazing things.',
        'Every step forward is a step toward success.',
        'The harder you work, the luckier you get.',
        'Stay positive, work hard, make it happen.',
        'Believe in yourself.',
        'Never give up on your dreams.',
        'Your only limit is your mind.',
        'Stay positive, work hard, make it happen.',
        'Stay positive, work hard, make it happen.',
        'Your only limit is your mind.',
        'Stay positive, work hard, make it happen.',
        'Every step forward is a step toward success.',
        'Stay positive, work hard, make it happen.',
        'You are capable of amazing things.',
        'Your only limit is your mind.',
        'Believe in yourself.',
        'You are capable of amazing things.',
        'Push through the pain.',
        'Push through the pain.',
        'Believe in yourself.',
        'Dream big and dare to fail.',
        'Every step forward is a step toward success.',
        'Never give up on your dreams.',
        'Your only limit is your mind.',
        'Dream big and dare to fail.',
        'The harder you work, the luckier you get.',
        'Every step forward is a step toward success.',
        'Push through the pain.',
        'Every step forward is a step toward success.',
        'Stay positive, work hard, make it happen.',
        'Never give up on your dreams.',
        'Success starts with self-belief.',
        'Every step forward is a step toward success.',
        'Never give up on your dreams.',
        'Success starts with self-belief.',
        'Every step forward is a step toward success.',
        'Success starts with self-belief.',
        'Push through the pain.',
        'Never give up on your dreams.',
        'Success starts with self-belief.',
        'Push through the pain.',
        'You are capable of amazing things.',
        'Dream big and dare to fail.',
        'Every step forward is a step toward success.',
        'Never give up on your dreams.',
        'Success starts with self-belief.',
        'Push through the pain.',
        'Stay positive, work hard, make it happen.',
        'Push through the pain.',
        'Dream big and dare to fail.',
        'Success starts with self-belief.',
        'Success starts with self-belief.',
        'You are capable of amazing things.',
        'Believe in yourself.',
        'Stay positive, work hard, make it happen.',
        'Your only limit is your mind.',
        'You are capable of amazing things.',
        'Believe in yourself.',
        'Dream big and dare to fail.',
        'Success starts with self-belief.',
        'Every step forward is a step toward success.',
        'Never give up on your dreams.',
        'You are capable of amazing things.',
        'The harder you work, the luckier you get.',
        'Stay positive, work hard, make it happen.',
        'Stay positive, work hard, make it happen.',
        'Never give up on your dreams.',
        'Dream big and dare to fail.',
        'Believe in yourself.',
        'Believe in yourself.',
        'Dream big and dare to fail.',
        'The harder you work, the luckier you get.',
        'Push through the pain.',
        'Success starts with self-belief.',
        'Every step forward is a step toward success.',
        'Every step forward is a step toward success.',
        'Believe in yourself.',
        'The harder you work, the luckier you get.',
        'Your only limit is your mind.',
        'The harder you work, the luckier you get.',
        'Every step forward is a step toward success.',
        'The harder you work, the luckier you get.',
        'Push through the pain.',
        'Every step forward is a step toward success.',
        'Stay positive, work hard, make it happen.',
        'The harder you work, the luckier you get.',
        'Stay positive, work hard, make it happen.',
        'Never give up on your dreams.',
        'You are capable of amazing things.',
        'Dream big and dare to fail.',
        'Stay positive, work hard, make it happen.',
        'The harder you work, the luckier you get.',
        'Dream big and dare to fail.',
        'Believe in yourself.',
        'Never give up on your dreams.',
        'Every step forward is a step toward success.',
        'Success starts with self-belief.',
        'Success starts with self-belief.',
        'Dream big and dare to fail.',
        'Every step forward is a step toward success.',
        'Success starts with self-belief.',
        'Your only limit is your mind.',
        'Stay positive, work hard, make it happen.',
        'Believe in yourself.',
        'Your only limit is your mind.',
        'Every step forward is a step toward success.',
        'Success starts with self-belief.',
        'Push through the pain.',
        'Never give up on your dreams.',
        'Every step forward is a step toward success.',
        'Dream big and dare to fail.',
        'Your only limit is your mind.',
        'Never give up on your dreams.',
        'Every step forward is a step toward success.',
        'Success starts with self-belief.',
        'Push through the pain.',
        'The harder you work, the luckier you get.',
        'Believe in yourself.',
        'Push through the pain.',
        'You are capable of amazing things.',
        'Dream big and dare to fail.',
        'You are capable of amazing things.',
        'Success starts with self-belief.',
        'Stay positive, work hard, make it happen.',
        'You are capable of amazing things.',
        'Believe in yourself.',
        'Stay positive, work hard, make it happen.',
        'Every step forward is a step toward success.',
        'Every step forward is a step toward success.',
        'Your only limit is your mind.',
        'Dream big and dare to fail.',
        'The harder you work, the luckier you get.',
        'Believe in yourself.',
        'Success starts with self-belief.',
        'Never give up on your dreams.',
        'Push through the pain.',
        'Never give up on your dreams.',
        'Push through the pain.',
        'Believe in yourself.',
        'Believe in yourself.',
        'Stay positive, work hard, make it happen.',
        'Believe in yourself.',
        'Stay positive, work hard, make it happen.',
        'You are capable of amazing things.',
        'Never give up on your dreams.',
        'Every step forward is a step toward success.',
        'Push through the pain.',
        'Dream big and dare to fail.',
        'Believe in yourself.',
        'Stay positive, work hard, make it happen.',
        'Believe in yourself.',
        'Stay positive, work hard, make it happen.',
        'You are capable of amazing things.',
        'Your only limit is your mind.',
        'You are capable of amazing things.',
        'Believe in yourself.',
        'Push through the pain.',
        'Stay positive, work hard, make it happen.',
        'Stay positive, work hard, make it happen.',
        'Believe in yourself.',
        'Every step forward is a step toward success.',
        'The harder you work, the luckier you get.',
        'Every step forward is a step toward success.',
        'Push through the pain.',
        'You are capable of amazing things.',
        'Success starts with self-belief.',
        'Dream big and dare to fail.',
        'Success starts with self-belief.',
        'Never give up on your dreams.',
        'Stay positive, work hard, make it happen.',
        'Every step forward is a step toward success.',
        'Success starts with self-belief.',
        'Believe in yourself.',
        'You are capable of amazing things.',
        'Your only limit is your mind.',
        'Success starts with self-belief.',
        'Believe in yourself.',
        'Believe in yourself.',
        'The harder you work, the luckier you get.',
        'Your only limit is your mind.',
        'You are capable of amazing things.',
        'Stay positive, work hard, make it happen.',
        'Success starts with self-belief.',
        'Every step forward is a step toward success.',
        'Dream big and dare to fail.',
        'You are capable of amazing things.',
        'Every step forward is a step toward success.',
        'Believe in yourself.'
    ];

    function cheerMeUp() public view returns (string memory) {
        uint256 randomIndex = uint256(keccak256(abi.encodePacked(block.timestamp, block.prevrandao))) % messages.length;
        return messages[randomIndex];
    }

}
